### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by T7890u** [ragibmondal/hamstarcombat-clone#1]
Can i contact you personally

**Comment by T7890u** [comment]
Unexpected Application Error!
Cannot read properties of null (reading 'energy')
TypeError: Cannot read properties of null (reading 'energy')
    at vw (https://hamster-kombat-clone-alpha.vercel.app/static/js/main.f63cc716.js:2:535725)
    at go (https://hamster-kombat-clone-alpha.vercel.app/static/js/main.f63cc716.js:2:60553)
    at Al (https://hamster-kombat-clone-alpha.vercel.app/static/js/main.f63cc716.js:2:120229)
    at ku (https://hamster-kombat-clone-alpha.vercel.app/static/js/main.f63cc716.js:2:109329)
    at _u (https://hamster-kombat-clone-alpha.vercel.app/static/js/main.f63cc716.js:2:109257)
    at Eu (https://hamster-kombat-clone-alpha.vercel.app/static/js/main.f63cc716.js:2:109120)
    at cu (https://hamster-kombat-clone-alpha.vercel.app/static/js/main.f63cc716.js:2:105898)
    at uu (https://hamster-kombat-clone-alpha.vercel.app/static/js/main.f63cc716.js:2:104449)
    at _ (https://hamster-kombat-clone-alpha.vercel.app/static/js/main.f63cc716.js:2:138359)
    at MessagePort.N (https://hamster-kombat-clone-alpha.vercel.app/static/js/main.f63cc716.js:2:138893)

**Comment by ElonTusk404** [comment]
I have such problem too

**Comment by isanat** [comment]
let's help each other?

I want to install it too, and I didn't get to this part that you did.

my whatsapp +55 18996426306
